const uiConstants = {
  headers: {
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    ERROR_404: '404',
    ERROR_500: '500',
    CHAT_LIST: 'Chat list',
    USERS_LIST: 'Users list',
    DELETE_CHAT: 'Delete chat',
    DELETE_USER: 'Delete user',
    ADD_USER: 'Add User',
    CREATE_CHAT: 'Create chat',
    CHANGE_PASSWORD: 'Change password',
  },
  text: {
    PAGE_NOT_FOUND: 'Page not found',
    INTERNAL_SERVER_ERROR: 'Internal server error',
  },
  buttons: {
    LOGIN: 'Login',
    REGISTER: 'Register',
    CREATE_ACCOUNT: 'Create account',
    HAVE_ACCOUNT: 'Have an account?',
    GO_BACK: 'Go back',
    SAVE: 'Save',
    CHANGE_PASSWORD: 'Change password',
    DELETE: 'DELETE',
    ADD: 'Add',
    CREATE: 'Create',
  },
  placeholders: {
    LOGIN: 'login',
    EMAIL: 'email',
    FIRST_NAME: 'first name',
    LAST_NAME: 'last name',
    PHONE_NUMBER: 'phone number',
    DISPLAY_NAME: 'display name',
    PASSWORD: 'password',
    CURRENT_PASSWORD: 'current password',
    NEW_PASSWORD: 'new password',
    REPEAT_PASSWORD: 'repeat password',
    SEARCH: 'Search',
    MESSAGE: 'Message',
    ENTER_USER_LOGIN: 'Enter user login',
    ENTER_CHAT_TITLE: 'Enter chat title',
  },
  errors: {
    LOGIN_VALIDATION_FAILED: 'Login should not be less then 3 letters',
    PASSWORD_VALIDATION_FAILED: 'Your password is not strong enough',
    MAIL_VALIDATION_FAILED: 'Please enter currect email adress',
    PHONE_VALIDATION_FAILED: 'Please enter currect phone number',
    FIRST_NAME_VALIDATION_FAILED: 'Please enger currect first name',
    SECOND_NAME_VALIDATION_FAILED: 'Please enger currect last name',
    SEARCH_VALIDATION_FAILED: 'Should not be empty',
    MESSAGE_VALIDATION_FAILED: 'Message should not be empty',
    WRONG_PASSWORD: 'wrong password',
    LOGIN_DOES_NOT_EXIST: 'login does not extist',
    PASSWORDS_DO_NOT_MATCH: 'passwords do not match',
    FORM_VALIDATION_FAILED: 'Please fill out all required field',
  },
  warnings: {
    DELETE_CHAT: 'Are you sure you want to delete chat',
    DELETE_USER: 'Are you sure you want to delete user',
  },
  palette: {
    PRIMARY: '#bb86fc',
    LIGHT: '#c89efc',
    DARK: '#825db0',
    ON_PRIMARY: '#ffffff',
  },
  settings: {
    edit_mode: true,
  },
  routes: {
    INDEX: '/',
    REGISTER: '/sing-up',
    PROFILE: '/settings',
    CHAT: '/messenger',
  },
  BASE_URL: 'https://ya-praktikum.tech/api/v2',
  PROTECTED_ROUTE: "PROTECTED_ROUTE"
};

export default uiConstants;
